name: atempo_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
# icon
  cupertino_icons: ^1.0.2
  radial_button: ^1.0.1
  font_awesome_flutter: ^10.8.0
  animated_music_indicator: ^0.0.6
  animated_toggle_switch: ^0.8.3
# 기본 설정
  change_app_package_name: ^1.4.0
  circular_menu: ^4.0.0
  dartdoc: ^8.1.0
  flutter_expanded_tile: ^0.4.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.6
  form_model: ^1.0.2+2
  go_router: ^9.0.0
  get: ^4.6.6
  intl: ^0.19.0
  package_info_plus: ^8.1.2
# Uid생성
  uuid: ^4.5.1
# 음악플레이어
  just_audio: ^0.9.41
# 파이어베이스 관련
  cloud_firestore: ^5.4.3
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_storage: ^12.3.3
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  kakao_flutter_sdk: ^1.9.6
# 캘린더
  flutter_calendar_carousel: ^2.4.3
  table_calendar: ^3.0.9


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo_atempo_1.png"
  android_gravity: fill
  ios_content_mode: center
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: "assets/images/android_atempo_logo1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  #remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/button/
    - assets/images/main_emotion/
    - assets/images/main_emotion/square_icon/
    - assets/images/detailed_emotion/

  fonts:
    - family: Santteut
      fonts:
        - asset: assets/fonts/HakgyoansimSantteutdotumL.ttf
          weight: 600
        - asset: assets/fonts/HakgyoansimSantteutdotumM.ttf
          weight: 400

    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900


