// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK6Mvrpl5RP5TF7mgHtc0xxAgy-OdMFqg',
    appId: '1:525382879421:web:34111271252a57fdc70fd4',
    messagingSenderId: '525382879421',
    projectId: 'teamatempo',
    authDomain: 'teamatempo.firebaseapp.com',
    storageBucket: 'teamatempo.appspot.com',
    measurementId: 'G-2KBZZJFN4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWfS4iz-BCBAfJY0ERu07pgKeG9l6o3c',
    appId: '1:525382879421:android:b678e69a9fa9acedc70fd4',
    messagingSenderId: '525382879421',
    projectId: 'teamatempo',
    storageBucket: 'teamatempo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdguzCmhbjSF0jj36U8taMfLCb-P5hQ2M',
    appId: '1:525382879421:ios:f8121a012fcefd16c70fd4',
    messagingSenderId: '525382879421',
    projectId: 'teamatempo',
    storageBucket: 'teamatempo.appspot.com',
    iosClientId: '525382879421-i34brdpinog4odsmmbbd5tcvl5mndap8.apps.googleusercontent.com',
    iosBundleId: 'com.hongniest.atempo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdguzCmhbjSF0jj36U8taMfLCb-P5hQ2M',
    appId: '1:525382879421:ios:ff441b51c4ee3fc2c70fd4',
    messagingSenderId: '525382879421',
    projectId: 'teamatempo',
    storageBucket: 'teamatempo.appspot.com',
    iosClientId:
        '525382879421-jnvs0uis8jidd68fq1de7m5ptrkarh9j.apps.googleusercontent.com',
    iosBundleId: 'com.hongniest.atempo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK6Mvrpl5RP5TF7mgHtc0xxAgy-OdMFqg',
    appId: '1:525382879421:web:0b99c7c9326d8f7cc70fd4',
    messagingSenderId: '525382879421',
    projectId: 'teamatempo',
    authDomain: 'teamatempo.firebaseapp.com',
    storageBucket: 'teamatempo.appspot.com',
    measurementId: 'G-2B145JRLSR',
  );
}